export const Route = {
  about: '/about',
  budgets: '/budgets',
  budget: (budgetUUID: string) => `/budgets/${budgetUUID}`,
  category_purchases: (budgetUUID: string, categoryUUID: string) =>
    `/budgets/${budgetUUID}/categories/${categoryUUID}`,
  categories: (budgetUUID: string) => `/budgets/${budgetUUID}/categories`,
  calculators: '/calculators',
  contact: '/contact',
  dashboard: '/dashboard',
  home: '/',
  login: '/login',
  logout: '/logout',
  paydown: '/paydown',
  privacy: '/privacy',
  reset: '/reset',
  resetComplete: '/reset/complete',
  signup: '/signup',
  terms: '/terms',
  verifyEmail: '/verify-email',
} as const;
